version: '3.8'

services:
  nats:
    image: nats:2.10-alpine
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - ./config/nats.conf:/etc/nats/nats.conf
    command: ["-c", "/etc/nats/nats.conf", "-js", "-m", "8222"]

  vault:
    image: hashicorp/vault:1.13
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    cap_add:
      - IPC_LOCK
    command: vault server -dev
    restart: unless-stopped

  ipfs:
    image: ipfs/go-ipfs:latest
    container_name: ipfs
    ports:
      - "4001:4001"       # Swarm
      - "5001:5001"       # API
      - "8080:8080"       # Gateway
    restart: unless-stopped