version: '3.8'

services:
  nats:
    image: nats:2.10-alpine
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - ./config/nats.conf:/etc/nats/nats.conf
    command: ["-c", "/etc/nats/nats.conf", "-js", "-m", "8222"]

  vault:
    image: hashicorp/vault:1.13
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    cap_add:
      - IPC_LOCK
    command: vault server -dev
    restart: unless-stopped

  ipfs:
    image: ipfs/go-ipfs:latest
    container_name: ipfs
    ports:
      - "4001:4001"       # Swarm
      - "5001:5001"       # API
      - "8080:8080"       # Gateway
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: authdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  metadata-db:
    image: postgres:15-alpine
    container_name: metadata-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: metadb
    ports:
      - "5433:5432"
    volumes:
      - metadata_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
  metadata_data: